services:
  sampleapi:
    container_name: sampleapi
    build:
      context: .
      dockerfile: SampleApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - OTEL_SERVICE_NAME=sampleapi
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://datadog-agent:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development,host.name=test-host
      - ASPNETCORE_URLS=http://+:8080        
    depends_on:
      - datadog-agent
  datadog-agent:
    container_name: datadog-agent
    image: "gcr.io/datadoghq/agent:latest"
    pid: host
    ports:
      - 8126:8126
      - 4317:4317
      - 4318:4318
    environment:
      - DD_API_KEY=
      - DD_SITE=datadoghq.eu  # Datadog site
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_OTLP_CONFIG_LOGS_ENABLED=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: my-next-app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://sampleapi:8080/api
    depends_on:
      - sampleapi